### ISSUE TITLE
URL issue

### ISSUE THREAD

**Issue by arev0007** [MTM6201-Web-Dev-II/grid-layout-with-flex-components#2]
Hello @abhaysharma,

 I have a problem with my URL. When I want to test my GitHub URL I cannot see the changes in it. 

I attached the URL: https://arev0007.github.io/grid-layout-with-flex-components/

How should I proceed on that?

Thank You,

Aldana

**Comment by abhaysharma** [comment]
@arev0007  this is the original repository, you need to add your issue in your repository under your account.
